Page({
    data:{
        src:'../imgs/right.png',
        list:[
            {
                option:'平台介绍'
            },
            {
                option:'安全保障'
            },
            {
                option:'注册/登陆'
            },
            {
                option:'购买理财'
            },
            {
                option:'支付提现'
            },
            {
                option:'债券转让'
            }
        ],
        test:'没有解决问题？请联系客服'
    }
})